name: Generate Snake Animation ğŸ

on:
  schedule:
    - cron: '0 22 * * *'  # Ã s 22h UTC (primeira execuÃ§Ã£o)
    - cron: '0 0 * * *'   # todo dia Ã  meia-noite UTC (execuÃ§Ãµes seguintes)
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositÃ³rio
        uses: actions/checkout@v3

      - name: Gerar cobrinha ğŸ
        uses: Platane/snk@v3
        with:
          github_user_name: guilhermehgz
          outputs: |
            ./github-contribution-grid-snake.svg

      - name: Commit e push da cobrinha
        uses: EndBug/add-and-commit@v9
        with:
          message: "ğŸ Atualizando cobrinha"
          add: "github-contribution-grid-snake.svg"
